### PR TITLE
Added script to generate fake ETC data for testing

### PR DESCRIPTION
**Pull request by paulmartini**
Added script to bin/ to generate simulated ETC data, and added the simulated data file to data/

### CODE REVIEW

**Comment by parfa30** [comment]
Paul, the data you produce looks good. However, when I try to run your code from bin `python fake_etc.py` I get the following error: `SystemError: <built-in function ensure_datetime64ns> returned a result with an error set`. This happens on line 49 where the dataframe is initialized.

**Comment by parfa30** [comment]
I found this error goes away if you add a time unit after datetime64.
For example:
`('start_time', 'datetime64'),` --> `('start_time', 'datetime64[s]'),` as defined in dtype.

**Comment by paulmartini** [comment]
Thanks for checking that, Parker. I've added that changed and pushed the update to the repo. Would you now merge the branch?

**Comment by paulmartini** [comment]
Sorry, I accidentally closed the pull request. I'm reopening it with the updated code.

**Comment by parfa30** [comment]
excellent, thanks for making the change! I'll merge it and close everything

**Pull request merged**
