### PR TITLE
Update data and layouts

### LINKED ISSUE #22: Spectral trace coordinates and wavelength calibration vs. environmental parameters
Include dx (trace shift) and dy (shift in wavelength direction) from each camera for each spectroscopic exposure. This is to enable studies of changes in where the spectra are dispersed on the detector vs. environmental conditions, especially in the Shack. Note this is motivated by Julien'Guy's discovery of a correlation between trace shift and Shack humidity in the blue and red cameras.

### LINKED ISSUE #24: Selection based on flavor
Flavors include science, dark, etc. We should be able to look at only certain data based on this.

### LINKED ISSUE #30: Add binning to Detector page
Several things on other pages aren't yet on the detector page.

### LINKED ISSUE #31: attrs all CAPS or lower()
Style of attributes in lists are all over the place. Make all lower or upper case.

### LINKED ISSUE #44: Improve positioner data
The data_script.py doesn't build the positioner files. These need to be improved.

### LINKED ISSUE #46: Spectrograph Page Cleanup
On the Spectrograph page, when the Category is "Spectrograph" I think it does not make sense to have the attribute be specific to an individual camera (although I know that is the way the data are stored). For example, if I set "X Category" to Observation and "Y Category" to Spectrograph and then choose to plot EXPID vs. humidity, I have to set the Y Attribute to "nir_camera_humidity_mean" for all three plots. I think it would be more useful to have 'camera_humidity' and 'camera_temp' and then plot the nir_camera_humidity_mean in the "NIR Detectors" panel, red_camera_humidity_mean in the "Red Detectors" panel, etc. At least I can't forsee wanting to plot nir_camera_humidity_mean vs. properties of the other two cameras. 

Note that this isn't true for all attributes under the "Spectrograph" category. The bench temps (and ieb temp) are not specific to cameras.

### PR DESCRIPTION
**Pull request by parfa30**
Lots of work done in this pull request.
- Positioner data updates
- POS selection options updated
- Fixed spectrograph page issues
- Improved layout
- Added binning to all pages
- Added selection based on data flavor

### CODE REVIEW

**Comment by paulmartini** [comment]
Hi @parfa30 - I was not able to get your branch to run. Here is the error message I obtained:

2020-09-30 10:54:19,941 Starting Bokeh server version 2.1.1 (running on Tornado 6.0.4)
2020-09-30 10:54:19,944 User authentication hooks NOT provided (default user enabled)
2020-09-30 10:54:19,947 Bokeh app running at: http://localhost:5006/instperfapp
2020-09-30 10:54:19,947 Starting Bokeh server with process id: 74027
2020-09-30 10:54:47,840 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x11e8038b0>: No objects to concatenate
File "concat.py", line 329, in __init__:
raise ValueError("No objects to concatenate") Traceback (most recent call last):
  File "/Users/martini.10/anaconda3/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/Users/martini.10/Repos/desiperf/py/desiperf/instperfapp/main.py", line 68, in <module>
    fp_tab, pp_tab, sp_tab = init_pages(DH)
  File "/Users/martini.10/Repos/desiperf/py/desiperf/instperfapp/main.py", line 41, in init_pages
    page.run()
  File "/Users/martini.10/Repos/desiperf/py/desiperf/instperfapp/pages/positioner.py", line 181, in run
    self.get_pos_data()
  File "/Users/martini.10/Repos/desiperf/py/desiperf/instperfapp/pages/positioner.py", line 120, in get_pos_data
    data = pd.concat(dd)
  File "/Users/martini.10/anaconda3/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 271, in concat
    op = _Concatenator(
  File "/Users/martini.10/anaconda3/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
 
I haven't managed to track down where this is coming from yet. I'm posting this here in case you recognize something.

**Comment by parfa30** [comment]
Hi Paul, thanks for posting this! I think I know the issue. I changed the positioner data files quite a bit but I don't think I committed them. I don't want to commit all 5000 so I'll commit a handful of them and see if that works.

**Comment by parfa30** [comment]
@paulmartini new files are added. Perhaps give it another try?

**Comment by paulmartini** [comment]
Hi @parfa30 - Thanks, now working and new layout and other changes look really slick. I'm really excited about this tool! 

I did encounter a few minor issues when testing the new version:
 - Error message in terminal: "BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead" 
 - Spectrograph Page: x-axis label and x-axis tickmarks not showing up 
 - Spectrograph Page: I set X and Y categories to Shack and was not able to plot space_temp_avg vs. time_recorded. I thought this would give me a plot of the Shack temp vs. time. 
I didn't exhaustively test, but will test some more in the next few days. And look into timing, etc. 

Also, I found one odd thing that I wanted to document. On the Focal Plane Page, I happened to plot ccdtemp_mean vs. skyra and there appears to be a correlation. I can't think of a reason why, but this is probably worth looking into. And this is really what this application is for, so that is exciting! 
 
I'm going ahead with the merge.

**Pull request merged**
